const { CommunityMembers } = require('../models');

const communityMembersData = [
    { user_id: 1, community_id: 1},
    { user_id: 1, community_id: 2},  
    { user_id: 2, community_id: 1}, 
    { user_id: 3, community_id: 1}, 
    { user_id: 4, community_id: 1}, 
    { user_id: 5, community_id: 1}, 
    { user_id: 6, community_id: 1}, 
    { user_id: 7, community_id: 1}, 
    { user_id: 8, community_id: 1}, 
    { user_id: 9, community_id: 1}, 
    { user_id: 10, community_id: 1}, 
    { user_id: 11, community_id: 1}, 
    { user_id: 12, community_id: 1}, 
    { user_id: 13, community_id: 1}, 
    { user_id: 14, community_id: 1}, 
    { user_id: 15, community_id: 1}, 
    { user_id: 16, community_id: 1}, 
    { user_id: 17, community_id: 1}, 
    { user_id: 18, community_id: 1}, 
    { user_id: 19, community_id: 1}, 
    { user_id: 20, community_id: 1}, 
    { user_id: 21, community_id: 2}, 
    { user_id: 22, community_id: 2}, 
    { user_id: 23, community_id: 2}, 
    { user_id: 24, community_id: 2}, 
    { user_id: 25, community_id: 2}, 
    { user_id: 26, community_id: 2}, 
    { user_id: 27, community_id: 2}, 
    { user_id: 28, community_id: 2}, 
    { user_id: 29, community_id: 2}, 
    { user_id: 30, community_id: 2}, 
    { user_id: 31, community_id: 2}, 
    { user_id: 32, community_id: 2}, 
    { user_id: 33, community_id: 2}, 
    { user_id: 34, community_id: 2}, 
    { user_id: 35, community_id: 2}, 
    { user_id: 36, community_id: 3}, 
    { user_id: 37, community_id: 3}, 
    { user_id: 38, community_id: 3}, 
    { user_id: 39, community_id: 3}, 
    { user_id: 40, community_id: 3}, 
    { user_id: 41, community_id: 3}, 
    { user_id: 42, community_id: 3}, 
    { user_id: 43, community_id: 3}, 
    { user_id: 44, community_id: 3}, 
    { user_id: 45, community_id: 3}, 
    { user_id: 46, community_id: 3}, 
    { user_id: 47, community_id: 3}, 
    { user_id: 48, community_id: 3}, 
    { user_id: 49, community_id: 3},
    { user_id: 49, community_id: 1},
    { user_id: 49, community_id: 2}, 
    { user_id: 50, community_id: 3}
];

const seedCommunityMembers = () => CommunityMembers.bulkCreate(communityMembersData);

module.exports = seedCommunityMembers;